AdvectionDiffusionBDF.C, AdvectionDiffusionBDF.h, SIMAD.h, Test/Square-abd1-ad-bdf2.reg, Test/Square-abd1-ad-be.reg, Test/Square-abd1-ad-bs.reg, Test/Square-abd1-ad-cn.reg, Test/Square-abd1-ad-euler.reg, Test/Square-abd1-ad-fehlberg.reg, Test/Square-abd1-ad-heun.reg, Test/Square-abd1-ad-heuneuler.reg, Test/Square-abd1-ad-rk3.reg, Test/Square-abd1-ad-rk4.reg, Test/Square-abd2-ad-bdf2.reg, Test/Square-abd2-ad-be.reg, Test/Square-abd2-ad-bs.reg, Test/Square-abd2-ad-cn.reg, Test/Square-abd2-ad-euler.reg, Test/Square-abd2-ad-fehlberg.reg, Test/Square-abd2-ad-heun.reg, Test/Square-abd2-ad-heuneuler.reg, Test/Square-abd2-ad-rk3.reg, Test/Square-abd2-ad-rk4.reg, Test/Square-ad-RaPr.reg, Test/Square-ad.reg
This contains prerequisits for mixed boussinesq support.
=> Preparations for mixed Boussinesq support

CMakeLists.txt, SIMAD.h, Test/MPI/Square-ad-restart.reg, Test/MPI/Square-ad-restart.xinp, Test/Square-abd2-ad-restart.reg, Test/Square-abd2-ad-restart.xinp, main_AdvectionDiffusion.C
Downstream of https://github.com/OPM/IFEM/pull/137
=> added: proper restart support

AdvectionDiffusion.C, AdvectionDiffusion.h, AdvectionDiffusionBDF.C, AdvectionDiffusionBDF.h, AdvectionDiffusionExplicit.C, AdvectionDiffusionExplicit.h
Downstream of OPM/IFEM#144.
Also some doxy-corrections here and there I spotted on the way and minor cosmetics.
=> Changed: Using fe.h instead of the static method which had an error anyway

main_AdvectionDiffusion.C
=> Changed: handleDataOutput is now a SIMSolver member

SIMAD.h, main_AdvectionDiffusion.C
=> Changed: Using the SIMSolverStat template

AdvectionDiffusion.C, AdvectionDiffusion.h, AdvectionDiffusionArgs.C, AdvectionDiffusionArgs.h, AdvectionDiffusionBDF.C, AdvectionDiffusionExplicit.C, main_AdvectionDiffusion.C
=>  Changed: Using SIMargsBase as parent of AdvectionDiffusionArgs 

SIMAD.h, main_AdvectionDiffusion.C
=>  Changed: Using base class SIMsolution to handle serialization 

AdvectionDiffusion.C, SIMAD.h, Test/MPI/Square-ad-restart.reg, Test/Square-abd2-ad-restart.reg
libcereal was not installed on AFEM, so these tests have not executed for a while.
=> Fix restart test

jenkins/build.sh
Downstream of https://github.com/OPM/IFEM/pull/333
=> make stokes and navierstokes sidestreams

AdvectionDiffusionBDF.C, SIMAD.h, Test/MPI/Square-ad-adap.reg
=>  Removed error message from reg-file

SIMAD.h
=> Changed: Use ROBIN instead of NEUMANN_GENERIC

AdvectionDiffusionBDF.C, AdvectionDiffusionExplicit.C, AdvectionDiffusionExplicit.h, CMakeLists.txt, SIMAD.h, Test/Square-abd2-ad-ab2.reg, Test/Square-abd2-ad-ab3.reg, Test/Square-abd2-ad-ab4.reg, Test/Square-abd2-ad-ab5.reg, Test/Square-abd2-ad-explicit-lmm.xinp, main_AdvectionDiffusion.C
Downstream of https://github.com/OPM/IFEM/pull/378
=> added: support for explicit multistep methods

AdvectionDiffusion.C, AdvectionDiffusion.h, AdvectionDiffusionImplicit.C, AdvectionDiffusionImplicit.h, CMakeLists.txt, SIMAD.h, Test/Square-abd2-ad-ab1.reg, Test/Square-abd2-ad-am1.reg, Test/Square-abd2-ad-am2.reg, Test/Square-abd2-ad-am3.reg, Test/Square-abd2-ad-am4.reg, main_AdvectionDiffusion.C
Downstream of https://github.com/OPM/IFEM/pull/389
=> Add implicit linear multistep support

SIMAD.h, Test/MPI/Square-2-LR-bdf2.reg, Test/MPI/Square-ad-adap.reg, Test/MPI/Square-ad-restart.reg, Test/Square-2-LR-bdf2.reg, Test/Square-abd2-ad-ab1.reg, Test/Square-abd2-ad-ab2.reg, Test/Square-abd2-ad-ab3.reg, Test/Square-abd2-ad-ab4.reg, Test/Square-abd2-ad-ab5.reg, Test/Square-abd2-ad-am1.reg, Test/Square-abd2-ad-am2.reg, Test/Square-abd2-ad-am3.reg, Test/Square-abd2-ad-am4.reg, Test/Square-abd2-ad-bdf2.reg, Test/Square-abd2-ad-be.reg, Test/Square-abd2-ad-bs.reg, Test/Square-abd2-ad-cn.reg, Test/Square-abd2-ad-euler.reg, Test/Square-abd2-ad-heun.reg, Test/Square-abd2-ad-heuneuler.reg, Test/Square-abd2-ad-restart.reg, Test/Square-abd2-ad-rk3.reg, Test/Square-abd2-ad-rk4.reg, Test/Square-ad-RaPr.reg, Test/Square-ad-adap-rec.reg, Test/Square-ad-adap-res.reg, Test/Square-ad-adap.reg, Test/Square-ad.reg
this fixes the relative error in the final norm output
=> fixed: unify adaptive and final norm output

ADFluidProperties.C, Test/Square-ad-RaPr.xinp
=> changed: use prandtlrayleigh as fluid property type

ADFluidProperties.C, ADFluidProperties.h, AdvectionDiffusion.C, AdvectionDiffusionBDF.C, AdvectionDiffusionImplicit.C
Downstream of https://github.com/OPM/IFEM/pull/409
=> added: allow specifying a function for rayleigh number

SIMAD.h
- allow a function for specifying maximum number of sub-iterations
- add a setting for what to do if subiterations fails to converge
- explicitly increase isrefined when clearProperties are called. this
to work with adaptive simulations where AdaptiveSIM is not involved
=> update subiteration support

AdvectionDiffusion.C, SIMAD.h
Plus some pretty-printing and a (potential) bug fix.
=> Subiteration refinement

main_AdvectionDiffusion.C
Downstream of https://github.com/OPM/IFEM/pull/433
=> solver template update - pass appropriate ProcessAdm

SIMAD.h
Downstream of https://github.com/OPM/IFEM/pull/478
=> put subiteration code in Boussinesq classes

CMakeLists.txt, SIMAD.C, SIMAD.h, main_AdvectionDiffusion.C
to limit rebuild cost and downstream build times
=> changed: make SIMAD a private template

Test/Square-abd2-ad-restart.reg
Downstream of https://github.com/OPM/IFEM/pull/499
=> minor regression test update

Common/AdvectionDiffusion/SIMAD.C
Sidestream of https://github.com/sintefmath/IFEM-Stokes/pull/203
=> changed: print temperature summary at msgLevel >= 1

Common/AdvectionDiffusion/SIMAD.C, Test/Square-ad-adap-rec.reg
easier when used in boussinesq
=> changed: print effectivity index as eta^T

Common/AdvectionDiffusion/AdvectionDiffusion.C
for clarity. no functional differences.
=> use proper variable names

CMakeLists.txt, Common/AdvectionDiffusion/CMakeLists.txt
To quell warnings on ubuntu jammy.
=> changed: bump minimum cmake version

CMakeLists.txt, Common/AdvectionDiffusion/CMakeLists.txt
Same as https://github.com/OPM/IFEM/pull/618
=> bump minimum cmake version and move required tag before project

Common/AdvectionDiffusion/SIMAD.C
also make sure we have projected norm entries before postprocessing
=> use unique_ptr

Common/AdvectionDiffusion/AdvectionDiffusion.h, Common/AdvectionDiffusion/SIMAD.C, Common/AdvectionDiffusion/SIMAD.h, main_AdvectionDiffusion.C
Various things needed to enable Marangoni simulations
=> Stuff required to add support for Marangoni simulations

Common/AdvectionDiffusion/AdvectionDiffusionBDF.C, Common/AdvectionDiffusion/AdvectionDiffusionImplicit.C
Downstream of https://github.com/OPM/IFEM/pull/680
=> adjust to flipped sign for Laplacian residual term

Test/Square-ad.vreg
=> Fixed: Primary solution component name and no exact vector field

Common/AdvectionDiffusion/AdvectionDiffusionSource.C, Common/AdvectionDiffusion/AdvectionDiffusionSource.h
needed in boussinesq
Sibling of https://github.com/OPM/IFEM/pull/696
=> added: add index of scalar solution to be used

Common/AdvectionDiffusion/AdvectionDiffusion.C, Common/AdvectionDiffusion/AdvectionDiffusion.h, Common/AdvectionDiffusion/AdvectionDiffusionBDF.h, Common/AdvectionDiffusion/AdvectionDiffusionExplicit.h, Common/AdvectionDiffusion/AdvectionDiffusionImplicit.h
remove unnecessary empty dtors and default constructor parameter values
=> mark constructors explicit

Common/AdvectionDiffusion/AdvectionDiffusion.C, Common/AdvectionDiffusion/AdvectionDiffusionBDF.C
Plus some other minor cosmetics which should not affect the calculations.
The use of Vec3 instead of Vector in the norm integration is natural since the fields involved is the gradient of the primary scalar field and will always have size `nsd`. The use of Vector is then unnecessary. The performance gain is probably minimal though, but the changes are needed when we soon refactor Vector to _not_ inherit std::vector.
=> Changed: Represent solution gradients by Vec3 in norm integration
